version: '3.8'
name: viet-itn
services:
  api:
    image: dangvansam/viet-itn:qwen-reasoning-with-vllm
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8006:8000"
