[project]
name = "viet-itn"
version = "0.1.0"
description = "Vietnamese Inverse Text Normalizer"
authors = [
    { name = "Sam Dang", email = "dangvansam98@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "fastapi",
    "openai>=1.93.0",
    "uvicorn",
]